server:
  port: 8002

spring:
   application:
    name: cloud-dept-provider

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: cloud-provider-dept-8002
    prefer-ip-address: true

info:
  app.name: alibaba-cloud-demo
  company.name: www.alibaba.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}