server: 
  port: 3344 
  
spring:
  application:
    name:  cloud-config
  cloud:
    config:
      server:
        git:
          uri: git@gitlab.alibaba-inc.com:xuliang.sxl/cloud-config.git

